### PR TITLE
publish

### PR DESCRIPTION
**Pull request by florin139**

### CODE REVIEW

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by florin139** [comment]
npm publish

**Comment by tradeshiftcicomponents** [comment]
:package: **npm publish** :package:

Pre-release of `@tradeshift/ng-translate-t` successfully published :rocket:

```
npm install @tradeshift/ng-translate-t@0.0.0-695f71241a2c39d64e1b9bd06971c44b1aa8131d
```

Happy testing :tophat:

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by florin139** [comment]
npm publish

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
:package: **npm publish** :package:

Pre-release of `@tradeshift/ng-translate-t` successfully published :rocket:

```
npm install @tradeshift/ng-translate-t@0.0.0-005a7a7f5cfec889b598720689e563e8289a85cf
```

Happy testing :tophat:

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by florin139** [comment]
npm publish

**Comment by tradeshiftcicomponents** [comment]
:package: **npm publish** :package:

Pre-release of `@tradeshift/ng-translate-t` successfully published :rocket:

```
npm install @tradeshift/ng-translate-t@0.0.0-d40345ebecb9a64459694644cf797f01e1de05ed
```

Happy testing :tophat:

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by florin139** [comment]
npm publish

**Comment by tradeshiftcicomponents** [comment]
:package: **npm publish** :package:

Pre-release of `@tradeshift/ng-translate-t` successfully published :rocket:

```
npm install @tradeshift/ng-translate-t@0.0.0-1fe83a00084a09ba57e4c76b75341c76ab1ca19e
```

Happy testing :tophat:

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Pull request closed without merging**
