### PR TITLE
fix vulns

### PR DESCRIPTION
**Pull request by florin139**
npm audit 
found 0 vulnerabilities

### CODE REVIEW

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

 No new version will be released.
                    If a release is expected, please fix commit messages to align with appropriate format :arrow_right: [Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md)

**Comment by tradeshiftcicomponents** [comment]
*Semantic release: ([Commit conventions](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md))*

## 1.0.2 (https://github.com/tradeshift/ng-translate-t/compare/v1.0.1...v1.0.2) (2022-05-05)

### Bug Fixes

 - vulns: updaate lins to fix current vulnerabilities (834fb7d (https://github.com/tradeshift/ng-translate-t/commit/834fb7d9d89dda050089d0175df74f915f3df5e6))

**Review by oanagoanta-td — APPROVED** [review]

**Review by adinaiordache2017 — APPROVED** [review]
👍

**Pull request merged**
